runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
 - name: flask
   version: "latest"

env_variables:
  TWILIO_ACCT_SID: "ACb6f607d4a8f1cc189f3d4d1eb19b8b3d"
  TWILIO_AUTH_TOKEN: "a750e19ea7b0e6815034ecbee260c52c"
  TWILIO_PHONE_NUM: "+12242796236"